import React from 'react'
import { IUser } from '../../../types/types';
import classes from './FeedLowerPart.module.scss';
import FeedPosts from './FeedPosts/FeedPosts';
import avatar from '../../../images/ToPimpAButterfly.png';
import { IPost } from './../../../types/types';

const FeedLowerPart = () => {
  const users: IUser[] = [
    {
      id: 1,
      email: 'qwerty@gmail.com',
      password: 'qwerty123',
      avatar: avatar,
      name: 'DuffGirl',
      id_name: 'ongod',
      status: 'hiii meeen',
      description: 'string',
      showcase_id: 1,
      is_photo_profile: true,
      is_activated: true,
      activation_link: 'aAIJSFHloaISgguasPASaGFaspgj',
      role_id: 0,
      is_banned: false,
      ban_reason: '',
      is_closed_profile: false,
      is_disabled_commenting_my_posts: false,
      who_can_tag_me: 0,    // 0 - все , 1 - только подписчики, 2 -только я
      who_can_send_me_messages: 0,
      is_notifications_enabled: true,
      show_notification_message_text: true,
    },
    {
      id: 2,
      email: 'qwerty@gmail.com',
      password: 'qwerty123',
      avatar: avatar,
      name: 'lupuwellness',
      id_name: 'lupuwellness',
      status: 'hiii meeen',
      description: 'string',
      showcase_id: 1,
      is_photo_profile: true,
      is_activated: true,
      activation_link: 'aAIJSFHloaISgguasPASaGFaspgj',
      role_id: 0,
      is_banned: false,
      ban_reason: '',
      is_closed_profile: false,
      is_disabled_commenting_my_posts: false,
      who_can_tag_me: 0,    // 0 - все , 1 - только подписчики, 2 -только я
      who_can_send_me_messages: 0,
      is_notifications_enabled: true,
      show_notification_message_text: true,
    },
    {
      id: 3,
      email: 'qwerty@gmail.com',
      password: 'qwerty123',
      avatar: avatar,
      name: 'MagaNaprogibkiday',
      id_name: 'ongod',
      status: 'hiii meeen',
      description: 'string',
      showcase_id: 1,
      is_photo_profile: true,
      is_activated: true,
      activation_link: 'aAIJSFHloaISgguasPASaGFaspgj',
      role_id: 0,
      is_banned: false,
      ban_reason: '',
      is_closed_profile: false,
      is_disabled_commenting_my_posts: false,
      who_can_tag_me: 0,    // 0 - все , 1 - только подписчики, 2 -только я
      who_can_send_me_messages: 0,
      is_notifications_enabled: true,
      show_notification_message_text: true,
    },
    {
      id: 3,
      email: 'qwerty@gmail.com',
      password: 'qwerty123',
      avatar: avatar,
      name: 'MagaNaprogibkiday',
      id_name: 'ongod',
      status: 'hiii meeen',
      description: 'string',
      showcase_id: 1,
      is_photo_profile: true,
      is_activated: true,
      activation_link: 'aAIJSFHloaISgguasPASaGFaspgj',
      role_id: 0,
      is_banned: false,
      ban_reason: '',
      is_closed_profile: false,
      is_disabled_commenting_my_posts: false,
      who_can_tag_me: 0,    // 0 - все , 1 - только подписчики, 2 -только я
      who_can_send_me_messages: 0,
      is_notifications_enabled: true,
      show_notification_message_text: true,
    },
    {
      id: 4,
      email: 'qwerty@gmail.com',
      password: 'qwerty123',
      avatar: avatar,
      name: 'MagaNaprogibkiday',
      id_name: 'ongod',
      status: 'hiii meeen',
      description: 'string',
      showcase_id: 1,
      is_photo_profile: true,
      is_activated: true,
      activation_link: 'aAIJSFHloaISgguasPASaGFaspgj',
      role_id: 0,
      is_banned: false,
      ban_reason: '',
      is_closed_profile: false,
      is_disabled_commenting_my_posts: false,
      who_can_tag_me: 0,    // 0 - все , 1 - только подписчики, 2 -только я
      who_can_send_me_messages: 0,
      is_notifications_enabled: true,
      show_notification_message_text: true,
    },
    {
      id: 5,
      email: 'qwerty@gmail.com',
      password: 'qwerty123',
      avatar: avatar,
      name: 'MagaNaprogibkiday',
      id_name: 'ongod',
      status: 'hiii meeen',
      description: 'string',
      showcase_id: 1,
      is_photo_profile: true,
      is_activated: true,
      activation_link: 'aAIJSFHloaISgguasPASaGFaspgj',
      role_id: 0,
      is_banned: false,
      ban_reason: '',
      is_closed_profile: false,
      is_disabled_commenting_my_posts: false,
      who_can_tag_me: 0,    // 0 - все , 1 - только подписчики, 2 -только я
      who_can_send_me_messages: 0,
      is_notifications_enabled: true,
      show_notification_message_text: true,
    },
    {
      id: 6,
      email: 'qwerty@gmail.com',
      password: 'qwerty123',
      avatar: avatar,
      name: 'MagaNaprogibkiday',
      id_name: 'ongod',
      status: 'hiii meeen',
      description: 'string',
      showcase_id: 1,
      is_photo_profile: true,
      is_activated: true,
      activation_link: 'aAIJSFHloaISgguasPASaGFaspgj',
      role_id: 0,
      is_banned: false,
      ban_reason: '',
      is_closed_profile: false,
      is_disabled_commenting_my_posts: false,
      who_can_tag_me: 0,    // 0 - все , 1 - только подписчики, 2 -только я
      who_can_send_me_messages: 0,
      is_notifications_enabled: true,
      show_notification_message_text: true,
    },
  ]

  const posts: IPost[] = [
    {id: 1, user_id: 1, image_id: 1, is_pinned_post: false, text: 'Привет!', album_id: 0, mentioned_user_id: 1, likes_count: 573, shares_count: 83, shared_post_id: 5, views: 4862, pub_date: '24.05.22 12:04'},
    {id: 2, user_id: 2, image_id: 0, is_pinned_post: false, text: '❗Stand-Up комик Сергей Детков рассказал в своем Instagram* аккаунте, что в скоре он будет посещать секцию Рукопашного боя.Пожелаем успехов Сереже в спорте, надеемся там у него все сложится🙏*запрещённая в России соцсеть ❗Stand-Up комик Сергей Детков рассказал в своем Instagram* аккаунте, что в скоре он будет посещать секцию Рукопашного боя.Пожелаем успехов Сереже в спорте, надеемся там у него все сложится🙏*запрещённая в России соцсеть', album_id: 0, mentioned_user_id: 1, likes_count: 573, shares_count: 83, shared_post_id: 5, views: 4862, pub_date: '24.05.22 12:04'},
    {id: 3, user_id: 3, image_id: 0, is_pinned_post: false, text: 'Привет!', album_id: 0, mentioned_user_id: 1, likes_count: 573, shares_count: 83, shared_post_id: 5, views: 4862, pub_date: '24.05.22 12:04'},
    {id: 4, user_id: 4, image_id: 0, is_pinned_post: false, text: 'Привет!', album_id: 0, mentioned_user_id: 1, likes_count: 573, shares_count: 83, shared_post_id: 5, views: 4862, pub_date: '24.05.22 12:04'},
    {id: 5, user_id: 5, image_id: 0, is_pinned_post: false, text: 'Привет!', album_id: 0, mentioned_user_id: 1, likes_count: 573, shares_count: 83, shared_post_id: 5, views: 4862, pub_date: '24.05.22 12:04'},
    {id: 6, user_id: 6, image_id: 0, is_pinned_post: false, text: 'Привет!', album_id: 0, mentioned_user_id: 1, likes_count: 573, shares_count: 83, shared_post_id: 5, views: 4862, pub_date: '24.05.22 12:04'},
  ]

  return (
    <div className={classes.FeedLowerPart}>
        <FeedPosts users={users} posts={posts}/>
    </div>
  )
}

export default FeedLowerPart